# Example config file for the Ethereum watcher.

beacon_url: http://localhost:5051/
beacon_type: other
execution_url: ~
web3signer_url: ~
default_fee_recipient: ~
slack_channel: ~
slack_token: ~
relays: ~
liveness_file: ~

watched_keys:
  - public_key: '0x832b8286f5d6535fd941c6c4ed8b9b20d214fc6aa726ce4fba1c9dbb4f278132646304f550e557231b6932aa02cf08d3'
    labels: ['google']
    fee_recipient: ~
